dist: trusty
language: node_js
node_js:
- stable
script:
- npm run coverage
after_success:
- npm run publish-coverage
branches:
only: development
email:
  recipients:
  - 1242313097@qq.com      # change to your own address
  on_success: never        # default: change
  on_failure: always       # default: always
